In [24]:
import torch
import numpy as np
torch.__version__

'1.10.2+cu113'

### Tensor
张量是一个统称，其中包含很多类型：是一个可以包含高维数据的统称的一个数据结构（类型）

1. 0阶张量：标量, scaler、常数，0-D Tensor . 在计算loss中, 返回的就是一个标量.

2. 1阶张量：向量 vector，1-D Tensor 

3. 2阶张量：矩阵 matrix，2-D Tensor

4. 3阶张量

5. ...

6. N阶张量

   这个阶也称之为维度, 即shape个数.

In [3]:
# 在python中创建Tensor
# 首先要区分的是torch.Tensor() 和 torch.tensor()
# 首先大写的Tensoe是类, 一般来说是传入形状然后生成未初始化的tensor. 我们可以通过类直接创建不同类型的tensor
# 而小的的tensor是方法, 一般来说是传入数据, 直接生成tensor. 我们可以指定dtype来控制数据类型
# 接下来我们就使用torch中的方法创建tensor

In [4]:
# 使用python中的list创建tensor
t1 = torch.tensor([[1, 3], [1, 4]])
t1.dtype # torch.int64
t1
# tensor([[1, 3],
        # [1, 4]])
        


tensor([[1, 3],
        [1, 4]])

In [5]:
#  使用数据直接创建tensor
torch.tensor(np.array(
    [[1, 2, 3],  
     [4, 5, 6]],
     dtype=np.float64 # 在np中指定dtype类型
)) # 那么生成的tensor类型也是与np类型相同的


tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)

In [6]:
# 使用Torch的API创建tensor：
# 1. 创建一个空的tenosr变量, 未初始化, 会用无用数据进行填充
torch.empty([4, 3])

tensor([[0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 2.8026e-45],
        [0.0000e+00, 1.1210e-44, 0.0000e+00]])

In [7]:
# 创建全为1 的tensor
torch.ones([4, 3])

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [8]:
# 创建全为0的tensor
torch.zeros([4, 5])

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [9]:
# 指定数值创建:
# 例子: 创建一个4*5的矩阵, 并全部用10进行填充
torch.full([4 ,5],10)

tensor([[10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10]])

In [10]:
# 随机创建_创建一个矩阵, 符合均匀分布, 范围: [0, 1)
torch.rand(size=(4, 3))
# 如果要创建到固定范围内: [a, b)
a = 5
b = 10

(b-a) * torch.rand(size=(4, 3)) + a

tensor([[5.4564, 9.3058, 5.7780],
        [7.3136, 7.3910, 5.1064],
        [5.5680, 5.5340, 8.8255],
        [5.7724, 5.4930, 9.5683]])

In [11]:
# 创建随机整数:
# 创建整数, 同样符合均匀分布
torch.randint(low=3, high=10, size=(4, 6))

tensor([[9, 8, 9, 9, 9, 8],
        [9, 3, 6, 7, 6, 9],
        [9, 3, 7, 6, 4, 9],
        [7, 9, 8, 7, 8, 7]])

In [12]:
# 创建随机tensor, 符合标准正态分布:
torch.randn(size=(4, 3))

tensor([[ 1.3156, -0.4003,  1.3474],
        [ 1.2182, -0.3865,  0.8569],
        [-0.8072,  1.0584,  1.5826],
        [ 1.2820, -0.0606,  0.7341]])

In [13]:
# 也可以让每个元素, 都服从不同的正太分布:
torch.normal(
    mean=torch.full(size=(10, 1), fill_value=10.),
    std=torch.full(size=(10,1), fill_value=4.0)
)
# 注意, 必须是类型是一样的,并且大小也要是一样的.
# 可以都指定为Float

tensor([[13.9482],
        [ 4.2463],
        [ 9.1501],
        [ 9.3327],
        [ 6.6901],
        [11.3228],
        [ 8.5560],
        [10.1490],
        [15.0447],
        [11.6420]])

### tensor的常用方法

In [14]:
# 当tensor中只有一个元素的时候, 我们可以直接使用该方法获取其中的元素值
# 不用在一层一层索引了
t2 = torch.tensor([[1]], dtype=torch.float32)
t2 # 此时如果我们需要取出里面的值我们需要一层一层索引:

tensor([[1.]])

In [15]:
t2[0][0]

tensor(1.)

In [16]:
# 但是我们可以直接使用: item()就直接可以得到其中的元素值
t2.item()

1.0

In [32]:
# 转换为numpy数组
t3 = torch.randn(size=(3, 4))
t3

tensor([[ 1.1523, -1.6463, -1.0331, -0.8791],
        [-1.9095, -2.6722,  1.7284, -0.8762],
        [ 0.2697,  0.4617, -0.1400,  0.5709]])

In [33]:
print("t3.numpy():",t3.numpy()) # 直接从tensor 转换到 ndarray
print(type(t3.numpy())) # 直接就是原地修改了。


t3.numpy(): [[ 1.152254   -1.6463319  -1.0331253  -0.87907887]
 [-1.909497   -2.6722298   1.728365   -0.8762252 ]
 [ 0.26970991  0.46171832 -0.14001462  0.5709199 ]]
<class 'numpy.ndarray'>


In [42]:
# 获取形状
t4 = torch.Tensor(size=(10, 20))
t4.size()

torch.Size([10, 20])