In [5]:
import torch
import numpy as np
torch.__version__ # 版本

'1.10.2+cu113'

### Tensor
张量是一个统称，其中包含很多类型：是一个可以包含高维数据的统称的一个数据结构（类型）

1. 0阶张量：标量, scaler、常数，0-D Tensor . 在计算loss中, 返回的就是一个标量.

2. 1阶张量：向量 vector，1-D Tensor 

3. 2阶张量：矩阵 matrix，2-D Tensor

4. 3阶张量

5. ...

6. N阶张量

   这个阶也称之为维度, 即shape个数.

In [3]:
# 在python中创建Tensor
# 首先要区分的是torch.Tensor() 和 torch.tensor()
# 首先大写的Tensoe是类, 一般来说是传入形状然后生成未初始化的tensor. 我们可以通过类直接创建不同类型的tensor
# 而小的的tensor是方法, 一般来说是传入数据, 直接生成tensor. 我们可以指定dtype来控制数据类型
# 接下来我们就使用torch中的方法创建tensor

In [12]:
# 使用python中的list创建tensor
t1 = torch.tensor([[1, 3], [1, 4]])
t1.dtype # torch.int64
t1
# tensor([[1, 3],
        # [1, 4]])
        


tensor([[1, 3],
        [1, 4]])

In [ ]:
#  使用数据直接创建tensor
torch.tensor(np.array(
    [[1, 2, 3],  
     [4, 5, 6]],
     dtype=np.float64 # 在np中指定dtype类型
)) # 那么生成的tensor类型也是与np类型相同的


tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)