In [14]:
import torch
import numpy as np
torch.__version__ # 版本

'1.10.2+cu113'

### Tensor
张量是一个统称，其中包含很多类型：是一个可以包含高维数据的统称的一个数据结构（类型）

1. 0阶张量：标量, scaler、常数，0-D Tensor . 在计算loss中, 返回的就是一个标量.

2. 1阶张量：向量 vector，1-D Tensor 

3. 2阶张量：矩阵 matrix，2-D Tensor

4. 3阶张量

5. ...

6. N阶张量

   这个阶也称之为维度, 即shape个数.

In [15]:
# 在python中创建Tensor
# 首先要区分的是torch.Tensor() 和 torch.tensor()
# 首先大写的Tensoe是类, 一般来说是传入形状然后生成未初始化的tensor. 我们可以通过类直接创建不同类型的tensor
# 而小的的tensor是方法, 一般来说是传入数据, 直接生成tensor. 我们可以指定dtype来控制数据类型
# 接下来我们就使用torch中的方法创建tensor

In [16]:
# 使用python中的list创建tensor
t1 = torch.tensor([[1, 3], [1, 4]])
t1.dtype # torch.int64
t1
# tensor([[1, 3],
        # [1, 4]])

tensor([[1, 3],
        [1, 4]])

In [17]:
#  使用数据直接创建tensor, 创建的时候就已经初始化了
torch.tensor(np.array(
    [[1, 2, 3],  
     [4, 5, 6]],
     dtype=np.float64 # 在np中指定dtype类型
)) # 那么生成的tensor类型也是与np类型相同的


tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)

In [35]:
# 利用形状创建tensor
t2 = torch.Tensor(4, 5) # 创建一个(1, 2)的tensor
print(t2)
print("dtype:", t2.dtype) # dtype: torch.float32

tensor([[1.0561e-38, 1.0653e-38, 4.1327e-39, 8.9082e-39, 9.8265e-39],
        [9.4592e-39, 1.0561e-38, 6.7041e-39, 1.1112e-38, 9.5511e-39],
        [1.0102e-38, 9.0918e-39, 1.0469e-38, 8.4490e-39, 1.0102e-38],
        [9.2755e-39, 8.9082e-39, 1.0653e-38, 1.0837e-38, 1.0561e-38]])
dtype: torch.float32


In [39]:
t3 = torch.DoubleTensor(5, 8)
print(t3)
print("dtype", t3.dtype) # dtype torch.float64

tensor([[1.5001e+248,  4.3117e-96,  1.1600e-28,  4.3160e-80, 1.9492e-153,
         1.6141e+132, 6.2920e+233, 9.8980e+164],
        [6.0135e-154, 2.8807e+214,  9.1628e-72,  7.6116e+93, 4.1933e+228,
          9.1628e-72, 5.5405e+228, 2.7257e+257],
        [8.7452e-154, 4.4036e+198,  2.9516e-75,  1.0884e-71, 8.8289e+199,
          9.1628e-72, 4.0667e+223, 7.2808e+223],
        [4.8241e+228, 2.5248e+180, 1.0610e-153, 3.1711e+180, 4.4439e+252,
         1.4418e+228, 6.7735e+276, 2.4513e+198],
        [4.6635e+223, 3.4213e+180, 6.7989e+199, 2.6636e+233, 2.3216e-152,
         7.2658e+223,  6.2401e-85, 4.9407e-324]], dtype=torch.float64)
dtype torch.float64


In [58]:
# 使用APi创建Tensor
# 1. torch.empty(): 创建未初始化的tensor., 里面是脏数据.
torch.empty((3, 1), dtype=torch.float)

tensor([[-2.9234e+24],
        [ 4.5909e-41],
        [ 0.0000e+00]])